AWSTemplateFormatVersion: 2010-09-09
Parameters:

  makeS3Bucket:
    Description: if true then ony you can make resource
    Type: String
    Default: true
    AllowedValues: [true,false]
  
  bucketName:
    Description: name of the bucket
    Type: String
    Default: bucket270520210356

  s3Access:
    Description: access of the bucket
    Type: String
    Default: Private
    AllowedValues: [Private,PublicRead,PublicReadWrite,AuthenticatedRead,LogDeliveryWrite,BucketOwnerRead,BucketOwnerFullControl]

Conditions:
  
  makeS3Resources: !Equals [ !Ref makeS3Bucket, true]

Resources: 

  s3Bucket:
    Condition: makeS3Resources
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: !Ref s3Access
      BucketName: !Ref  bucketName
      Tags:
        - Key: Created For
          Value: CodePipelineTest

Outputs:
  LogicalID:
    Condition: makeS3Resources
    Description: Information about the value
    Value: !Ref s3Bucket
    Export: 
      Name: "S3-BucketName"
