AWSTemplateFormatVersion: 2010-09-09
Parameters:

  bucketName:
    Description: name of the bucket
    Type: String
    Default: bucket270520210356

  s3Access:
    Description: access of the bucket
    Type: String
    Default: Private
    AllowedValues: [Private,PublicRead,PublicReadWrite,AuthenticatedRead,LogDeliveryWrite,BucketOwnerRead,BucketOwnerFullControl]


Resources: 

  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: !Ref s3Access
      BucketName: !Ref  bucketName
      Tags:
        - Key: Created For
          Value: CodePipelineTest

Outputs:
  LogicalID:
    Condition: makeS3Resources
    Description: Information about the value
    Value: !Ref s3Bucket
    Export: 
      Name: "S3-BucketName"
